---
- name: "Get current python3 version"
  shell: /usr/local/bin/python3 --version |sed 's/^Python //'
  register: python_version_current
  changed_when: 'python_version_current.stdout != python_version_default'
  check_mode: no

- block:
  - name: "Download python {{ python_version_default }} source code"
    get_url:
      url: https://www.python.org/ftp/python/{{ python_version_default }}/Python-{{ python_version_default }}.tgz
      dest: /usr/src/Python-{{ python_version_default }}.tgz
      mode: '0644'
    become: yes

  - name: "Unpack python {{ python_version_default }} source code"
    unarchive:
      src: /usr/src/Python-{{ python_version_default }}.tgz
      dest: /usr/src/
      remote_src: yes
    become: yes

  - name: "Run 'configure' target as root"
    command: chdir=/usr/src/Python-{{ python_version_default }} ./configure --prefix=/usr/local --enable-shared --with-threads --enable-optimization LDFLAGS="-Wl,-rpath /usr/local/lib"
    become: yes
    tags: skip_ansible_lint

  - name: "Run 'make install' target as root"
    make:
      chdir: /usr/src/Python-{{ python_version_default }}
      target: install
      file: /usr/src/Python-{{ python_version_default }}/Makefile
    notify: python installed
    become: yes
    tags: skip_ansible_lint

  - name: "Update alternatives for python2"
    command: update-alternatives --install /usr/bin/python python /usr/bin/python2 50
    become: yes
    tags: skip_ansible_lint

  - name: "Update alternatives for python3"
    command: update-alternatives --install /usr/bin/python python /usr/local/bin/python3.7 60
    become: yes
    tags: skip_ansible_lint

  - name: "Transfer python .so file to lib64"
    command: chdir=/usr/local/lib/ cp libpython3.7m.so.1.0 /lib64/
    become: yes
    tags: skip_ansible_lint

  - name: "Remove python source code archive"
    file:
      path: /usr/src/Python-{{ python_version_default }}.tgz
      state: absent
    become: yes
  when: 'python_version_current.stdout != python_version_default'
